[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@nanopub/nanopub-js", "@nanopub/sign"]

[dev]
  publish = "public"
  port = 9000
